server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: utf-8
      enabled: true

spring:
  devtools:
    restart:
      enabled: true

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://springboot-db-zzame.cvriwfemm5ms.ap-northeast-2.rds.amazonaws.com/devzzame
    username: devzzame
    password: ad04275319!

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        #show-sql: true
        format_sql: true


  servlet:
    multipart:
      enabled: true
      max-file-size: 2MB

  security:
    user:
      name: test
      password: 1234

    oauth2:
      client:
        registration:
          google:
            client-id: 870639976236-e59u023pnhjchl4k3do1u5q757sk1v7p.apps.googleusercontent.com
            client-secret: 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
            scope:

          naver:
            client-id: 6mJToSD9EVqNaPnvkCex
            client-secret: a2MzLnuD9n
            scope: name, email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8000/login/oauth2/code/naver

          kakao:
            client-id: ae8a8515a3cda0509639d12e47888da4
            redirect-uri: http://localhost:8000/login/oauth2/code/kakao
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope: profile_nickname, profile_image, account_email
            client-name: Kakao

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response # 회원정보를 json으로 받는데 response라는 키값으로 네이버가 리턴해줌
          kakao:
            authorization_uri: https://kauth.kakao.com/oauth/authorize
            token_uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user_name_attribute: id

file:
  path: /Users/zzame/Desktop/upload/

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

tnwls:
  key: tnwls1234

